/**
 * TextPlus Author - Modern Raconteur Authoring DSL
 * 
 * Main entry point for TextPlus Author library.
 * This will export the DSL parser, compiler, and linting tools.
 * 
 * Milestone 2 Implementation will add:
 * - DSL parser and lexer
 * - Compilation to TextPlus Core format
 * - Markdown content processing
 * - Adaptive text helpers (oneOf, randomly, etc)
 * - Situation linting and validation
 * - Project scaffolding CLI
 * - Hot module reloading support
 * - Situation graph visualization
 */

import { parseGame } from './parser';
import { compileAST } from './compiler';
import { lintAST, formatDiagnostics } from './linter';
import { workflowExecute, formatWorkflowReport, serializeWorkflowResult } from './workflow';

export const VERSION = '0.0.1';

export { parseGame };
export { compileAST };
export { lintAST, formatDiagnostics };
export { workflowExecute, formatWorkflowReport, serializeWorkflowResult };
export {
  tokenizeExpression,
  parseExpression,
  compileConditionExpr,
  collectQualityRefs,
  ExpressionError,
} from './expression';
export type { ExprNode, QualitiesRecord } from './expression';
export { parseEffects, compileEffects, collectEffectRefs, EffectError } from './effects';
export type { EffectNode } from './effects';
export {
  markdownToHtml,
  compileContent,
  hasDynamicContent,
  collectInterpolationRefs,
  createRng,
} from './content';
export type { CompiledContent, Rng } from './content';
export type {
  AuthorGameAst,
  AuthorHudNode,
  AuthorLinkNode,
  AuthorMisplacedDirective,
  AuthorPositions,
  AuthorQualityNode,
  AuthorQualityType,
  AuthorScheduleNode,
  AuthorSituationNode,
  AuthorTaskNode,
  AuthorThemeNode,
  AuthorWorldNode,
} from './parser';
export type { CompileError, CompileOutput, CompileAstOptions } from './compiler';
export type { LintDiagnostic, LintOutput, LintSeverity } from './linter';
export type { WorkflowResult, WorkflowOptions } from './workflow';

export interface CompileOptions {
  markdown?: boolean;
  validate?: boolean;
  linting?: boolean;
  /** Seed for adaptive-text randomness (tests); unseeded uses Math.random. */
  randomSeed?: number;
}

export interface CompileResult {
  game?: any;
  errors?: string[];
  warnings?: string[];
}

export function compileGame(source: string, options?: CompileOptions): CompileResult {
  const result = workflowExecute(source, { randomSeed: options?.randomSeed });

  return {
    game: result.config,
    errors: result.errors,
    warnings: result.warnings,
  };
}

export async function createScaffold(name: string, outputDir: string): Promise<void> {
  const { mkdir, writeFile } = await import('node:fs/promises');
  const { join } = await import('node:path');
  const root = join(outputDir, name);
  await mkdir(root, { recursive: true });

  const dsl = `title: ${name}
quality score number = 0 min 0 max 100

hud score meter "Score"

:: start [start]
Welcome to ${name}.

-> Continue => next { score += 10 }

:: next
This is your second situation. Your score stands at {score}.

-> End => end

:: end
Thanks for playing.
`;

  await writeFile(join(root, 'game.tp.txt'), dsl, 'utf8');
  await writeFile(
    join(root, 'README.md'),
    `# ${name}

Generated by @textplus/author createScaffold.

## Files

- game.tp.txt: Starter TextPlus DSL story.
`,
    'utf8',
  );
}
