import { describe, it, expect } from 'vitest';
import { mkdtemp, readFile, rm } from 'node:fs/promises';
import { tmpdir } from 'node:os';
import { join } from 'node:path';
import { compileGame, createScaffold } from '../../src';

describe('TextPlus Author - Public API', () => {
  it('compileGame returns compiled game for valid DSL', () => {
    const source = `title: API Test
:: start
Start
-> Next => next
:: next
Done
`;

    const result = compileGame(source);

    expect(result.game).toBeDefined();
    expect(result.game?.title).toBe('API Test');
    expect(result.errors).toHaveLength(0);
  });

  it('compileGame surfaces errors for invalid DSL', () => {
    const source = `title: Invalid
:: start
Start
-> Broken => missing
`;

    const result = compileGame(source);

    expect(result.game).toBeUndefined();
    expect((result.errors || []).length).toBeGreaterThan(0);
  });

  it('createScaffold creates starter files', async () => {
    const base = await mkdtemp(join(tmpdir(), 'textplus-author-'));

    try {
      await createScaffold('sample-game', base);

      const dsl = await readFile(join(base, 'sample-game', 'game.tp.txt'), 'utf8');
      const readme = await readFile(join(base, 'sample-game', 'README.md'), 'utf8');

      expect(dsl).toContain('title: sample-game');
      expect(readme).toContain('Generated by @textplus/author createScaffold.');
    } finally {
      await rm(base, { recursive: true, force: true });
    }
  });
});
